Update cast.py
Traceback (most recent call last):

  File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3550 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[3], line 1
    import clicast.editor

  File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/clicast/__init__.py:4
    from clicast.cast import Cast, CastReader

  File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/clicast/cast.py:248
    print header
    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?



To Fix the problem close the parentheses in line number [244, 245, 247]